### ISSUE TITLE
Question: Is it possible to not use CollectionFS?

### ISSUE THREAD

**Issue by jhenriquez** [yogiben/meteor-autoform-file#45]
I was wondering if I really need to upload/store the image some where in order to use this package. All I really want to do is display a user selected image in the form, and keep the path (of course). I would like to handle the persistence of the images later, together with my form.

I thought I could trick the package by not setting the collection option or using a dummy collection, but failed miserably.  Am I approaching this sideways?

Thanks in advance!

**Comment by jhenriquez** [comment]
Ok, I have not tried with a FS collection storing in the FileSystem. I think this may be enough. Thanks anyways!

**Comment by jhenriquez** [comment]
Hey,

It seems to be working as expected. Except, that I'm getting the _id from the CollectionFS document. I would love to get an actual FS path.

```
Schemas.Image = new SimpleSchema
  path:
    type: String
    autoform:
      afFieldInput:
        type: 'fileUpload'
        collection: Images
```

This is my simple schema, I'm using this as an array in other schema. It works, but I get the _id stored in the path field, which makes sense. Can I change this?
